/**:
  ros__parameters:
    # Local elevation map: small, fast, robot-centric, fixed in odom (smooth).
    map_frame: 'odom'
    base_frame: 'os_sensor'
    corrected_map_frame: 'odom'

    initialize_frame_id: ['os_sensor']
    initialize_tf_offset: [0.0]

    map_length: 20.0
    resolution: 0.1

    update_pose_fps: 10.0
    update_variance_fps: 5.0
    map_acquire_fps: 5.0
    recordable_fps: 3.0

    service_namespace: '/elevation_mapping_local'

    subscribers:
      lidar:
        topic_name: '/glim_ros/points'
        data_type: pointcloud

    publishers:
      elevation_map_raw:
        layers: ['elevation', 'traversability', 'variance']
        basic_layers: ['elevation']
        fps: 5.0
      elevation_map_filter:
        layers: ['min_filter', 'smooth', 'inpaint', 'elevation']
        basic_layers: ['min_filter']
        fps: 3.0
